version: '3.9'

services:
  adminer:
    container_name: adminer_container
    image: adminer
    restart: always
    ports:
      - 8080:8080

  postgres:
    container_name: postgres_container
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - ./initdb/init-postgres-db.sql:/docker-entrypoint-initdb.d/init-postgres-db.sql:ro

  mongo:
    container_name: mongo_container
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'